#!/bin/bash 

# PURPOSE: do vagrant setup common to all hosts in this project
#          steps that should run last after host specfic config


V_HOME=/home/vagrant/


chown vagrant.vagrant $V_HOME/.ssh -R
